In [1]:
import pandas as pd

In [2]:
columns = ['game_id', 'upvotes', 'downvotes', 'username', 'numgames', 'num_reviews', 'recommend', 'hours_played', 'date', 'review_text']

  * game id
  * number of people that found the review to be useful
  * number of people that found the review to be funny
  * username of the reviewer
  * number of games owned by the reviewer
  * number of reviews written by the reviewer
  * 1=recommended, -1=not recommended
  * hours played by the reviewer on the game
  * date of creation of the review
  * text of the review

In [4]:
data = pd.read_csv("data/reviews_new.csv", names = columns)

In [5]:
data

,game_id,upvotes,downvotes,username,numgames,num_reviews,recommend,hours_played,date,review_text
0,1429500,6,0,motaku96,0,39,1,2.3,"3 June, 2023","I'm still very early, this review is based on ..."
1,1429500,0,0,76561198068808490,0,2,1,7.4,"3 June, 2023","Pretty good game so far. Fun bosses, personall..."
2,1429500,0,0,76561197977706762,0,42,1,16.1,"12 May, 2023","A very well made game, bravo"
3,1429500,0,0,76561198436254738,92,23,1,8.6,"4 May, 2023",I am changing my review to recommended. I prev...
4,1429500,0,0,76561198280992237,0,5,1,12.0,"29 April, 2023",cant wait for full release
...,...,...,...,...,...,...,...,...,...,...
326455,1419170,0,0,SodaIsBae,64,6,1,48.4,"17 December, 2022",Bum Bum Bum Bum Bummmmm Bum Bum Bum Bummmmm Bum
326456,1419170,2,3,76561199065753238,0,6,1,91.7,"24 November, 2022",doooo dodoooo dodododooooooooo doooo dodo dodo...
326457,1419170,1,0,76561198211763701,0,1,1,20.6,"13 November, 2023",i love this game
326458,1419170,0,0,SodaIsBae,64,6,1,48.4,"17 December, 2022",Bum Bum Bum Bum Bummmmm Bum Bum Bum Bummmmm Bum
326459,1419170,2,3,76561199065753238,0,6,1,91.7,"24 November, 2022",doooo dodoooo dodododooooooooo doooo dodo dodo...

In [6]:
game_cols = ['_', "game_id", "game_name"]

In [7]:
gamedata = pd.read_csv("data/games.csv", names = game_cols)

In [8]:
gamedata

        _  game_id                               game_name
0     app  1144200                            Ready or Not
1     app  2524890                Pixel Gun 3D: PC Edition
2     app   976730       Halo: The Master Chief Collection
3     app  1517290                       Battlefieldâ„¢ 2042
4     app  2429860  Living With Sister: Monochrome Fantasy
...   ...      ...                                     ...
2055  app   502500            ACE COMBATâ„¢ 7: SKIES UNKNOWN
2056  app   962130                                Grounded
2057  app   740130                          Tales of Arise
2058  app  1222140                   Detroit: Become Human
2059  app  1902690                    Fate/Samurai Remnant

[2060 rows x 3 columns]

In [10]:
# Perform left join
result = pd.merge(data, gamedata, on='game_id', how='left')

In [16]:
result = result.drop(columns = ["_"])
result

,game_id,upvotes,downvotes,username,numgames,num_reviews,recommend,hours_played,date,review_text,game_name
0,1429500,6,0,motaku96,0,39,1,2.3,"3 June, 2023","I'm still very early, this review is based on ...",Frontier Hunter: Erzaâ€™s Wheel of Fortune
1,1429500,0,0,76561198068808490,0,2,1,7.4,"3 June, 2023","Pretty good game so far. Fun bosses, personall...",Frontier Hunter: Erzaâ€™s Wheel of Fortune
2,1429500,0,0,76561197977706762,0,42,1,16.1,"12 May, 2023","A very well made game, bravo",Frontier Hunter: Erzaâ€™s Wheel of Fortune
3,1429500,0,0,76561198436254738,92,23,1,8.6,"4 May, 2023",I am changing my review to recommended. I prev...,Frontier Hunter: Erzaâ€™s Wheel of Fortune
4,1429500,0,0,76561198280992237,0,5,1,12.0,"29 April, 2023",cant wait for full release,Frontier Hunter: Erzaâ€™s Wheel of Fortune
...,...,...,...,...,...,...,...,...,...,...,...
326455,1419170,0,0,SodaIsBae,64,6,1,48.4,"17 December, 2022",Bum Bum Bum Bum Bummmmm Bum Bum Bum Bummmmm Bum,American Truck Simulator - Oklahoma
326456,1419170,2,3,76561199065753238,0,6,1,91.7,"24 November, 2022",doooo dodoooo dodododooooooooo doooo dodo dodo...,American Truck Simulator - Oklahoma
326457,1419170,1,0,76561198211763701,0,1,1,20.6,"13 November, 2023",i love this game,American Truck Simulator - Oklahoma
326458,1419170,0,0,SodaIsBae,64,6,1,48.4,"17 December, 2022",Bum Bum Bum Bum Bummmmm Bum Bum Bum Bummmmm Bum,American Truck Simulator - Oklahoma
326459,1419170,2,3,76561199065753238,0,6,1,91.7,"24 November, 2022",doooo dodoooo dodododooooooooo doooo dodo dodo...,American Truck Simulator - Oklahoma

In [14]:
len(list(result.game_name.unique()))

274

In [17]:
result.to_csv("steam-reviews.csv")

In [18]:
import shutil
shutil.make_archive("data.zip", 'zip', "data")

'/media/ntu/volume1/home/s123md303_06/visualdialog/steam-crawler/data.zip.zip'